; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
;default_envs = JC2432W328C
;default_envs = esp32-3248S035C
default_envs = JC3248W535C
;default_envs = esp32-8048S043C
;default_envs = JC8048W550C
;default_envs = esp32-8048S070C

[env]
;pioarduino - espressif Arduino 3.3.4 and IDF 5.5.1.251106
;https://github.com/pioarduino/platform-espressif32
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino

;lib_deps = 
;	lvgl/lvgl@^9.2.2
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
monitor_filters = esp32_exception_decoder
build_flags =
  '-D BOARD_NAME="${this.board}"'
  ;'-D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO'
  '-D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_DEBUG'
  ;'-D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_VERBOSE'

[env:JC2432W328C]
board = JC2432W328C
build_flags = 
    -DTOUCH_SDA=33
    -DTOUCH_SCL=32
    -DTOUCH_RST=21
    -DTOUCH_INT=25
    -DSD_CS=5
    -DROTATION=1
    -DGFX_BL=27
    -DDISPLAY_WIDTH=240
    -DDISPLAY_HEIGHT=320
    -DSMALL

;[env:esp32-3248S035C]
;board = esp32-3248S035C
;build_flags = 
;    -DTOUCH_SDA=19
;    -DTOUCH_SCL=20
;    -DTOUCH_RST=38
;    -DTOUCH_INT=-1
;    -DSD_CS=10
;    -DROTATION=0
;    -DGFX_BL=2
;    -DDISPLAY_WIDTH=320
;    -DDISPLAY_HEIGHT=480
;    -DSMALL

[env:JC3248W535C]
board = JC3248W535C
build_flags = 
    -DGFX_BL=1
    -DROTATION=1
    -DDISPLAY_WIDTH=320
    -DDISPLAY_HEIGHT=480
    -DSD_CS=10
    -DCANVAS
    -DSMALL

[env:esp32-8048S043C]
board = esp32-8048S043C
build_flags = 
    -DTOUCH_SDA=19
    -DTOUCH_SCL=20
    -DTOUCH_RST=38
    -DTOUCH_INT=-1
    -DSD_CS=10
    -DROTATION=0
    -DGFX_BL=2
    -DDISPLAY_WIDTH=800
    -DDISPLAY_HEIGHT=480
    -DRGB_PANEL
    -DMEDIUM

[env:JC8048W550C]
board = JC8048W550C
build_flags = 
    -DTOUCH_SDA=19
    -DTOUCH_SCL=20
    -DTOUCH_RST=38
    -DTOUCH_INT=-1
    -DSD_CS=10
    -DROTATION=0
    -DGFX_BL=2
    -DDISPLAY_WIDTH=800
    -DDISPLAY_HEIGHT=480
    -DRGB_PANEL
    -DMEDIUM

;[env:esp32-8048S070C]
;board = esp32-8048S070C
;build_flags = 
;    -DTOUCH_SDA=19
;    -DTOUCH_SCL=20
;    -DTOUCH_RST=38
;    -DTOUCH_INT=-1
;    -DSD_CS=10
;    -DROTATION=0
;    -DGFX_BL=2
;    -DRGB_PANEL
;    -DDISPLAY_WIDTH=800
;    -DDISPLAY_HEIGHT=480
;    -DRGB_PANEL
;    -DLARGE
